server:
  port: 9901
spring:
  application:
    name: tensquare-base #给当前微服务起个名字
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.235.150:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/